//! Rewrite registry — maps user-typed commands to their `tokenlens`-prefixed
//! equivalents — and TOML filter-rule registry shared with `filter.rs`.
//!
//! Filter TOML files live in `filters/*.toml` and are embedded at build time.

use crate::filter::CompiledRule;
use once_cell::sync::Lazy;
use regex::Regex;
use serde::Deserialize;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RewriteAction { Allow, Rewrite, Deny, Ask }

#[derive(Debug, Clone)]
pub struct Rewrite {
    pub action: RewriteAction,
    pub command: String,
    pub reason: &'static str,
}

const SUPPORTED_PREFIXES: &[(&str, &str)] = &[
    ("git ", "git"),
    ("cargo ", "cargo"),
    ("npm ", "npm"),
    ("pnpm ", "pnpm"),
    ("yarn ", "yarn"),
    ("pytest", "pytest"),
    ("ruff ", "ruff"),
    ("mypy ", "mypy"),
    ("ls ", "ls"),
    ("tree ", "tree"),
    ("cat ", "read"),
    ("grep ", "grep"),
    ("find ", "find"),
    ("tsc", "tsc"),
    ("next ", "next"),
    ("vitest", "vitest"),
    ("jq ", "jq"),
    ("terraform ", "terraform"),
    ("helm ", "helm"),
    ("kubectl ", "kubectl"),
    ("docker ", "docker"),
    ("curl ", "curl"),
    ("wget ", "wget"),
    ("aws ", "aws"),
    ("gcloud ", "gcloud"),
];

const DENY_PREFIXES: &[&str] = &[];

/// Rewrite a single command line.
pub fn rewrite_command(cmd: &str) -> Rewrite {
    let trimmed = cmd.trim();
    if trimmed.is_empty() {
        return Rewrite { action: RewriteAction::Allow, command: cmd.to_string(), reason: "empty" };
    }
    if trimmed.starts_with("tokenlens ") || trimmed.starts_with("rtk ") {
        return Rewrite { action: RewriteAction::Allow, command: trimmed.to_string(), reason: "already-wrapped" };
    }
    for p in DENY_PREFIXES {
        if trimmed.starts_with(p) {
            return Rewrite { action: RewriteAction::Deny, command: trimmed.to_string(), reason: "deny-rule" };
        }
    }
    for (prefix, _category) in SUPPORTED_PREFIXES {
        if trimmed.starts_with(prefix) {
            return Rewrite {
                action: RewriteAction::Rewrite,
                command: format!("tokenlens {}", trimmed),
                reason: "supported-prefix",
            };
        }
    }
    Rewrite { action: RewriteAction::Allow, command: trimmed.to_string(), reason: "passthrough" }
}

/// Returns the whole compiled set of TOML filter rules, lazily loaded.
pub fn filter_rules() -> &'static FilterRules { &FILTER_RULES }

#[derive(Debug)]
pub struct FilterRules {
    rules: Vec<CompiledRule>,
}

impl FilterRules {
    pub fn match_cmd(&self, cmd: &str) -> Option<&CompiledRule> {
        self.rules.iter().find(|r| r.match_command.is_match(cmd))
    }
    pub fn len(&self) -> usize { self.rules.len() }
    pub fn is_empty(&self) -> bool { self.rules.is_empty() }
}

#[derive(Debug, Deserialize)]
struct RawFilterFile {
    #[serde(default)]
    filters: std::collections::BTreeMap<String, RawFilter>,
}

#[derive(Debug, Deserialize)]
struct RawFilter {
    #[serde(default)]
    description: Option<String>,
    match_command: String,
    #[serde(default)]
    strip_ansi: bool,
    #[serde(default)]
    strip_lines_matching: Vec<String>,
    #[serde(default)]
    max_lines: Option<usize>,
    #[serde(default)]
    truncate_lines_at: Option<usize>,
}

// Embed every TOML file in filters/ at compile time.
//
// `include_str!` macros live in `embedded.rs` (auto-generated by build.rs in a
// future iteration). For now we embed a small curated set inline so the
// library always builds — the rest are loaded at runtime from the filters/
// directory shipped alongside the binary if present.
include!("embedded.rs");

static FILTER_RULES: Lazy<FilterRules> = Lazy::new(|| {
    let mut rules: Vec<CompiledRule> = Vec::new();
    for (name, body) in EMBEDDED_FILTERS {
        match toml::from_str::<RawFilterFile>(body) {
            Ok(raw) => {
                for (filter_name, raw) in raw.filters {
                    if let Some(c) = compile(&format!("{name}::{filter_name}"), &raw) {
                        rules.push(c);
                    }
                }
            }
            Err(e) => eprintln!("[tokenlens] bad filter {name}: {e}"),
        }
    }
    FilterRules { rules }
});

fn compile(name: &str, raw: &RawFilter) -> Option<CompiledRule> {
    let _ = &raw.description;
    let match_command = Regex::new(&raw.match_command).ok()?;
    let strip_patterns = raw
        .strip_lines_matching
        .iter()
        .filter_map(|p| Regex::new(p).ok())
        .collect();
    Some(CompiledRule {
        name: name.to_string(),
        match_command,
        strip_ansi: raw.strip_ansi,
        strip_patterns,
        max_lines: raw.max_lines,
        truncate_lines_at: raw.truncate_lines_at,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rewrites_git_diff() {
        let r = rewrite_command("git diff");
        assert_eq!(r.action, RewriteAction::Rewrite);
        assert_eq!(r.command, "tokenlens git diff");
    }

    #[test]
    fn allows_unknown() {
        let r = rewrite_command("echo hi");
        assert_eq!(r.action, RewriteAction::Allow);
    }

    #[test]
    fn already_wrapped_passthrough() {
        let r = rewrite_command("tokenlens git diff");
        assert_eq!(r.action, RewriteAction::Allow);
    }

    #[test]
    fn embedded_filters_compile() {
        // At least one rule should compile from the embedded set.
        assert!(filter_rules().len() >= 1);
    }
}
